apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: multitool
  name: multitool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multitool
  template:
    metadata:
      labels:
        app: multitool
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool:openshift-minimal
        volumeMounts:
        - name: vol
          mountPath: /input
      - name: busybox
        image: busybox
        command: [ 'sh', '-c', 'watch -n 5 date > /output/success.txt' ]
        volumeMounts:
        - name: vol
          mountPath: /output
      volumes:
      - name: vol
        hostPath:
          path: /var/data


apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: multitool-log
  namespace: kube-system
  labels:
    app: multitool-log
spec:
  selector:
    matchLabels:
      name: multitool-log
  template:
    metadata:
      labels:
        name: multitool-log
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool:openshift-minimal
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log