apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: multitool-log
  labels:
    app: multitool-log
spec:
  selector:
    matchLabels:
      name: multitool-log
  template:
    metadata:
      labels:
        name: multitool-log
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool:openshift-minimal
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log/syslog
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log/syslog