apiVersion: v1
kind: Secret
metadata: 
  name: secret-tls
data:
  server-key.pem: |
    TUlJRXZBSUJBREFOQmdrcWhraUc5dzBCQVFFRkFBU0NCS1l3Z2dTaUFnRUFBb0lCQVFDbmtoUEh2
    amwxbzVwSQogICAgL3JFcCtkcmRWUmkvL1g5U01rT2VYTXhTOXN1THJVUnRVK240MHd3OUo0Q2xk
    dlBId2hFVTgrRG5kb0VjZUFpTQogICAgQTU5RXFIVU11QzRLb1EzK1QrVFk2eU5rcUFLN0Y0Q3dM
    U1VVU2RRVElTN1FpNmZSRTRBc3MrMEZ2SEQvVlhwUAogICAgVmJFUmtkTDFPcnVjZTRQYVRhbTMx
    S3F6WGJTTzRHaXZNbUFHYkJlVWt4R0ZpUExQenhJOFB6Ym1JRHkzN3Y3dgogICAgZGtXREErdzlB
    YkE1QmhQYmErS0NZejFyaktUOWNwMWZubGx0WVdUT09wRlNRQmgxTEdsZG9zNWpCT0ZEeEdZSgog
    ICAgS3ZHeU5YdjBPNE44c1NwQ0pyRTBOOEhqUytMSXdrMno3NVZUaGhxbXY2MTkyVElKU2lFK244
    eFp6aTl0NW5FVQogICAgZCtuU1UreDNBZ01CQUFFQ2dnRUFKYkNVODEzRlJjRGxBRnNNMVJDbUdo
    YzhTRjZIaHlEWUZhUHdydzVrYk1ldAogICAgZHR1amFmeHFLYzBiUWR3MTY2MnFNdWpCb3I0RVB6
    ZCtVS08xN0hicFVOR1NSWURCQ1h6Rno4WmZnUkhLLzNMRAogICAgVnB6bzFKM2diZWNPUlFqTVY1
    bkh3QVkrSHdhcDhid3psT21FdUp0d2RBamdUc3QzTmlBMnRxckdOQzYwNEZlYQogICAgNzR2OHha
    dkV1MFBzcDRiNFZ0eTBpWDQrbE1GZ0w4L0kvNTZtOUpQcUhSN1RFMkVnM0VCNTV3TzBlWE14Sitr
    MAogICAgVHpWRzc5MnFwTnIwbFhuZWk4N0tVQU1jcTh4R3hGaU5UQ2svS2EvcHBDNS93bFAwNEkz
    ckNwQmRWZ0VFam1VcwogICAgQlVIYlB0NzJuaUxzTURpYmczT21BS1BkbFlaQjY5TkpkQjlxbmVw
    aFhRS0JnUURVME0xVGNuMk82YjFwbERMTAogICAgM0dQZE5pbVoyeDAxYzZJZDlrenVTbXFDQnpn
    dUVucE96SXpmOUwzbnB4Uk9VekVrcXZ1aFFTVVBMOXk3dHlYRAogICAgUWw4MmwyaVYzWmlJRDF4
    RWFhVkVna1RyL1QvNlBqTlp2QW1XT0RSSFZxYmdDVUVSWStOb04xL04zSkRmN1VHYgogICAgazBr
    U0IrYWs5M0lmamhEeDRCemVLcHcwL1FLQmdRREprdXNuQ1BXYTVMNFhHZzl0U0N0bTd2U0pWd3U2
    OWd0bwogICAgZHVvSER5VnZGdlB4Q1R4RWdqNWxiS253QUl4NVQ0aElOOWU2NDJWc3hNTjFpblVS
    SWpYS0tydDBlNU8xdkE1SAogICAgc21RS0dqejQwMmRSUmR3czJ5RVpJcGlsaVFqbGkvajk5UkE1
    QXR3Rlg5eFNKczNMalJ1My8vRGp4R3JJRmYrWAogICAgQm13QUYzQzdnd0tCZ0RYYVFKc0ZOZENj
    UlZvYUxtQjMvSzFWcjJGSG1UU1Zka2l1c3ZqNXk4bnJtY1BPMlRSbgogICAgZnA2TmlDQytudHpU
    SUhSdThBMzJOaktKb2dtK1pzZnFXNzJzd3NKcHVOZDFTNXZrUC9YK0lRSzJxeUhmNjQ2aAogICAg
    anF0OHZYM3Y1M3A1M1FWUmlaSXRzUWllNytvNlY0Zk8xWWJDaVJMbHF2TmhOOWg5SmREeVoyVGhB
    b0dBZk9lLwogICAgTXljSUdmMFlGWFNlanBjajNkckFTTUpaa0hhYVJ4YzRtVHMzZFFrQ0RDQXU2
    anpTc1VLT1l4dlQ3Ky9xZ09XcAogICAgbGpNR1RFbjQzRUw1bTY1WktuY2tSVisxL2UwVDVEV1Vh
    L1lxUmYycGplRCtPQVZwRXd3dkRwUkZvUWdGT0VpOAogICAgenJjSTQ0T3RJSExQSHd6SFdsTU1U
    L2NNUEFQMXB2M2h1b1RMNUVVQ2dZQXU4ZzNvaUkwVjNDdW13Z0RpUGx6dAogICAgMTY2WU5MUzg3
    MUNuUFRFMkpuUWtVeWw3NENLQWI2eHROb3JOMnBPWmJiampJWFd6eXJRSkdQcFJNenI3QWhzWAog
    ICAgNFdscE9ta2luNTVUdFJBZ1FYQTVERHpLWG81blY3S1JlMVNHcE9EQU8yWlNLS0ZlZjBidzRm
    Rnk2RUNQTEhVVAogICAgaGNHZXo3TDdhWEFtY0ZudWJLR0hXdz09
  server.pem: |
    MIIDSzCCAjOgAwIBAgIUTBBdVy/5xAstuzUqVnzp0AKYZREwDQYJKoZIhvcNAQEL
    BQAwNTEYMBYGA1UEAwwPZXhhbXBsZS10ZXN0LnJ1MRkwFwYDVQQKDBBleGFtcGxl
    LXRlc3QucnUgMB4XDTI0MDYyNzE4MTcxN1oXDTI1MDYyNzE4MTcxN1owNTEYMBYG
    A1UEAwwPZXhhbXBsZS10ZXN0LnJ1MRkwFwYDVQQKDBBleGFtcGxlLXRlc3QucnUg
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAp5ITx745daOaSP6xKfna
    3VUYv/1/UjJDnlzMUvbLi61EbVPp+NMMPSeApXbzx8IRFPPg53aBHHgIjAOfRKh1
    DLguCqEN/k/k2OsjZKgCuxeAsC0lFEnUEyEu0Iun0ROALLPtBbxw/1V6T1WxEZHS
    9Tq7nHuD2k2pt9Sqs120juBorzJgBmwXlJMRhYjyz88SPD825iA8t+7+73ZFgwPs
    PQGwOQYT22vigmM9a4yk/XKdX55ZbWFkzjqRUkAYdSxpXaLOYwThQ8RmCSrxsjV7
    9DuDfLEqQiaxNDfB40viyMJNs++VU4Yapr+tfdkyCUohPp/MWc4vbeZxFHfp0lPs
    dwIDAQABo1MwUTAdBgNVHQ4EFgQUlTR4cOxFlFOH08GqlCyfbzgs4F0wHwYDVR0j
    BBgwFoAUlTR4cOxFlFOH08GqlCyfbzgs4F0wDwYDVR0TAQH/BAUwAwEB/zANBgkq
    hkiG9w0BAQsFAAOCAQEAd0GMSnTAJdsXaNQNqt5MBLHFPSDYB39mOS+EC/4ANxde
    3t+wfkwknRHWw8/3/eeYzQfB1m2myY/v6VOtiZMIPhVygMPXCXqY6dmPcJ7FMQJZ
    inguFEjHZhRRycGXIwDPlGGkkj0WU2a5Ci0uGlGEQigMWG8IEx3I8+34t/M5P9tW
    WL+v4IR91tkU0JlST1Xe5HZkTw31PvKoX65xReqwq41dy602ROeoljn0tax+573F
    d+KL8bx77ZV71gxX8u+kTgaSFaEs+6F+ULOdfRCccQlhXGATAYh/XaYAV03W4x1B
    Vb7nS2wa5EMzRnqUp5/bD5CEKmuIcO205epyG5H35A==

