apiVersion: v1
kind: Pod
metadata:
  labels:
    app: hello-world
  name: hello-world
  namespace: default
spec:
  containers:
  - image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
    name: hello-world