apiVersion: v1
kind: Service
metadata:
  name: netology-depl
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 80
  - name: multitool
    port: 1180
    protocol: TCP
    targetPort: 1180
  selector:
    app: nginx