apiVersion: v1
kind: Service
metadata:
  name: nginx-np
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
    nodePort: 30080
  - name: multitool
    port: 1180
    protocol: TCP
    nodePort: 31180
  selector:
    app: nginx
  type: NodePort