apiVersion: v1
kind: Service
metadata:
  name: deploy
spec:
  ports:
  - name: web
    port: 9001
    protocol: TCP
    targetPort: 80
  - name: multitool
    port: 9002
    protocol: TCP
    targetPort: 1180
  selector:
    app: nginx